<div style="text-align:center; font-size:90px"> Hackathon Data Projet 
<img src="logo.png" style="width:1200px; height:auto">
</div>

# Introduction :

# Références :

# Table de contenue :
- ### Analyse de données
- ### Cahier des charges
- ### Développement de module d'apprentissage
- ### Implémentation du solustion
- ### Coclusion

# 1 - Analyse des données

### 1-2. Sources dataset

- Le dataset fourni représente un enregistrement des interactions des utilisateurs avec différents produits sur un site e-commerce.
- Chaque ligne du dataset correspond à une action (vue) effectuée par un utilisateur à un instant donné, concernant un produit spécifique.

### 1-2. Qualité de chaque type de données

### 1-3. Preprocessing des données

### 1-4. Insights des données (Graphiques et analyse)

### 1-5. Commentaires

# Testing code

In [48]:
import pandas as pd
import numpy as np
import random

In [30]:
df = pd.read_csv("events.csv")
# pd.set_option('display.max_column', None)

In [31]:
df.head(10)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2020-09-24 11:57:06 UTC,view,1996170,2144415922528452715,electronics.telephone,NaN,31.90,1515915625519388267,LJuJVLEjPT
1,2020-09-24 11:57:26 UTC,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY
2,2020-09-24 11:57:27 UTC,view,215454,2144415927158964449,NaN,NaN,9.81,1515915625513238515,4TMArHtXQy
3,2020-09-24 11:57:33 UTC,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08
4,2020-09-24 11:57:36 UTC,view,3658723,2144415921169498184,NaN,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ
5,2020-09-24 11:57:59 UTC,view,664325,2144415951611757447,construction.tools.saw,carver,52.33,1515915625519388062,vnkdP81DDW
6,2020-09-24 11:58:23 UTC,view,3791349,2144415935086199225,computers.desktop,NaN,215.41,1515915625519388877,J1t6sIYXiV
7,2020-09-24 11:58:24 UTC,view,716611,2144415923694469257,computers.network.router,d-link,53.14,1515915625519388882,kVBeYDPcBw
8,2020-09-24 11:58:25 UTC,view,657859,2144415939431498289,NaN,NaN,34.17,1515915625519320570,HEl15U7JVy
9,2020-09-24 11:58:31 UTC,view,716611,2144415923694469257,computers.network.router,d-link,53.14,1515915625519388929,F3VB9LYp39

In [32]:
df['event_time'] = pd.to_datetime(df['event_time'])

In [33]:
df['Date'] = df['event_time'].dt.date
df['Heure'] = df['event_time'].dt.time

first_col = df.pop('Date')
second_col = df.pop('Heure')
last_col = df.pop('event_time')

df.insert(0, 'Date', first_col)
df.insert(1, 'Heure', second_col)
df.insert(10, 'event_time', last_col)

In [34]:
df.head()

,Date,Heure,event_type,product_id,category_id,category_code,brand,price,user_id,user_session,event_time
0,2020-09-24,11:57:06,view,1996170,2144415922528452715,electronics.telephone,NaN,31.90,1515915625519388267,LJuJVLEjPT,2020-09-24 11:57:06+00:00
1,2020-09-24,11:57:26,view,139905,2144415926932472027,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY,2020-09-24 11:57:26+00:00
2,2020-09-24,11:57:27,view,215454,2144415927158964449,NaN,NaN,9.81,1515915625513238515,4TMArHtXQy,2020-09-24 11:57:27+00:00
3,2020-09-24,11:57:33,view,635807,2144415923107266682,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08,2020-09-24 11:57:33+00:00
4,2020-09-24,11:57:36,view,3658723,2144415921169498184,NaN,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ,2020-09-24 11:57:36+00:00

In [35]:
distinct_event_types = df['event_type'].unique()
print(distinct_event_types)

['view' 'cart' 'purchase']

In [36]:
category_split = df['category_code'].str.split('.', expand=True)

df['categorie_1'] = category_split[0]
df['categorie_2'] = category_split[1]
df['categorie_3'] = category_split.iloc[: ,-1]

third_col = df.pop('categorie_1')
fourth_col = df.pop('categorie_2')
fifth_col = df.pop('categorie_3')

df.insert(5, 'categorie_1', third_col)
df.insert(6, 'categorie_2', fourth_col)
df.insert(7, 'categorie_3', fifth_col)

In [37]:
df.head(10)

,Date,Heure,event_type,product_id,category_id,categorie_1,categorie_2,categorie_3,category_code,brand,price,user_id,user_session,event_time
0,2020-09-24,11:57:06,view,1996170,2144415922528452715,electronics,telephone,None,electronics.telephone,NaN,31.90,1515915625519388267,LJuJVLEjPT,2020-09-24 11:57:06+00:00
1,2020-09-24,11:57:26,view,139905,2144415926932472027,computers,components,None,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY,2020-09-24 11:57:26+00:00
2,2020-09-24,11:57:27,view,215454,2144415927158964449,NaN,NaN,NaN,NaN,NaN,9.81,1515915625513238515,4TMArHtXQy,2020-09-24 11:57:27+00:00
3,2020-09-24,11:57:33,view,635807,2144415923107266682,computers,peripherals,None,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08,2020-09-24 11:57:33+00:00
4,2020-09-24,11:57:36,view,3658723,2144415921169498184,NaN,NaN,NaN,NaN,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ,2020-09-24 11:57:36+00:00
5,2020-09-24,11:57:59,view,664325,2144415951611757447,construction,tools,None,construction.tools.saw,carver,52.33,1515915625519388062,vnkdP81DDW,2020-09-24 11:57:59+00:00
6,2020-09-24,11:58:23,view,3791349,2144415935086199225,computers,desktop,None,computers.desktop,NaN,215.41,1515915625519388877,J1t6sIYXiV,2020-09-24 11:58:23+00:00
7,2020-09-24,11:58:24,view,716611,2144415923694469257,computers,network,None,computers.network.router,d-link,53.14,1515915625519388882,kVBeYDPcBw,2020-09-24 11:58:24+00:00
8,2020-09-24,11:58:25,view,657859,2144415939431498289,NaN,NaN,NaN,NaN,NaN,34.17,1515915625519320570,HEl15U7JVy,2020-09-24 11:58:25+00:00
9,2020-09-24,11:58:31,view,716611,2144415923694469257,computers,network,None,computers.network.router,d-link,53.14,1515915625519388929,F3VB9LYp39,2020-09-24 11:58:31+00:00

In [38]:
df.drop(columns=['event_time'], inplace=True)

In [49]:
longueur=19
# Séparer les lignes avec et sans valeurs NaN dans 'brand'
df['categorie_1'] = df['categorie_1'].fillna('not a category')
df['categorie_2']=df['categorie_2'].fillna('not a category')
df['categorie_3']=df['categorie_3'].fillna('not a category')
df['brand']= df["brand"].fillna('not a brand')
nombre = ''.join([str(random.randint(0, 9)) for _ in range(longueur)])
df['user_session'] = df['user_session'].fillna(nombre)

In [47]:
df

,Date,Heure,event_type,product_id,category_id,categorie_1,categorie_2,categorie_3,category_code,brand,price,user_id,user_session
0,2020-09-24,11:57:06,view,1996170,2144415922528452715,electronics,telephone,not a category,electronics.telephone,not a brand,31.90,1515915625519388267,LJuJVLEjPT
1,2020-09-24,11:57:26,view,139905,2144415926932472027,computers,components,not a category,computers.components.cooler,zalman,17.16,1515915625519380411,tdicluNnRY
2,2020-09-24,11:57:27,view,215454,2144415927158964449,not a category,not a category,not a category,NaN,not a brand,9.81,1515915625513238515,4TMArHtXQy
3,2020-09-24,11:57:33,view,635807,2144415923107266682,computers,peripherals,not a category,computers.peripherals.printer,pantum,113.81,1515915625519014356,aGFYrNgC08
4,2020-09-24,11:57:36,view,3658723,2144415921169498184,not a category,not a category,not a category,NaN,cameronsino,15.87,1515915625510743344,aa4mmk0kwQ
...,...,...,...,...,...,...,...,...,...,...,...,...,...
885124,2021-02-28,23:55:01,view,953226,2144415927553229037,not a category,not a category,not a category,NaN,not a brand,219.94,1515915625611023730,FRLqIttxKU
885125,2021-02-28,23:58:05,view,1715907,2144415927049912542,electronics,video,not a category,electronics.video.tv,starwind,80.03,1515915625611024014,g6WqPf50Ma
885126,2021-02-28,23:58:09,view,4170534,2144415939364389423,electronics,clocks,not a category,electronics.clocks,amazfit,64.92,1515915625611024020,xNIJBqZdkd
885127,2021-02-28,23:58:14,view,888273,2144415921932861531,electronics,telephone,not a category,electronics.telephone,not a brand,10.16,1515915625611024030,9pCbKMIcSx
885128,2021-02-28,23:59:09,view,743182,2144415935631458761,construction,tools,not a category,construction.tools.soldering,kada,65.08,1515915625556087775,BejOXRngEW

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 885129 entries, 0 to 885128
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           885129 non-null  object
 1   Heure          885129 non-null  object
 2   event_type     885129 non-null  object
 3   product_id     885129 non-null  int64
 4   category_id    885129 non-null  int64
 5   categorie_1    885129 non-null  object
 6   categorie_2    885129 non-null  object
 7   categorie_3    885129 non-null  object
 8   category_code  648910 non-null  object
 9   brand          885129 non-null  object
 10  price          885129 non-null  float64
 11  user_id        885129 non-null  int64
 12  user_session   885129 non-null  object
dtypes: float64(1), int64(3), object(9)
memory usage: 87.8+ MB

In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

# Load the dataset
df = pd.read_csv('events.csv')

# Handle missing values in other columns if any
# For categorical features: Impute missing values with the most frequent category
cat_cols = ['event_type', 'category_code', 'user_session']
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

# Preprocess 'event_time' column
df['event_time'] = pd.to_datetime(df['event_time'])  # Convert to datetime
df['year'] = df['event_time'].dt.year
df['month'] = df['event_time'].dt.month
df['day'] = df['event_time'].dt.day
df['hour'] = df['event_time'].dt.hour
df['minute'] = df['event_time'].dt.minute
df['second'] = df['event_time'].dt.second

# Drop the original 'event_time' column
df.drop(columns=['event_time'], inplace=True)

# Split the dataset into features and target
X = df.drop(columns=['brand'])
y = df['brand']

# Encode categorical features if needed
label_encoders = {}
for col in cat_cols:
    label_encoders[col] = LabelEncoder()
    X[col] = label_encoders[col].fit_transform(X[col])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Impute missing values in the 'brand' column with the most frequent brand
imputer = SimpleImputer(strategy='most_frequent')
y_train_imputed = imputer.fit_transform(y_train.values.reshape(-1, 1)).ravel()

# Train a Random Forest classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train_imputed)

# Predict missing values in the 'brand' column
y_test_imputed = rf_model.predict(X_test)

# Replace NaN values in the 'brand' column with predicted values
X_test['brand'] = y_test_imputed

# Updated DataFrame with imputed 'brand' column
updated_df = pd.concat([X_test, y_test], axis=1)

# Display the updated DataFrame
print(updated_df)

C:\Users\jorda\AppData\Local\Temp\ipykernel_25936\4361575.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

KeyboardInterrupt: